<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="pratik" name="Test1" tests="4" failures="4" timestamp="11 Mar 2016 09:30:37 GMT" time="72.568" errors="0">
  <testcase name="@AfterClass afterClassSwipeTest" time="0.0" classname="com.volProject.AppiumDemo.SwipeTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.volProject.AppiumDemo.SwipeTest.afterClassSwipeTest(SwipeTest.java:46)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass afterClassSwipeTest -->
  <testcase name="@AfterClass afterClassFirstTest" time="0.0" classname="com.volProject.AppiumDemo.CalcTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.volProject.AppiumDemo.CalcTest.afterClassFirstTest(CalcTest.java:59)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass afterClassFirstTest -->
  <testcase name="@AfterClass afterClassSecondTest" time="0.0" classname="com.volProject.AppiumDemo.SecondTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.volProject.AppiumDemo.SecondTest.afterClassSecondTest(SecondTest.java:46)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass afterClassSecondTest -->
  <testcase name="test1" time="0.008" classname="com.volProject.AppiumDemo.SwipeTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.volProject.AppiumDemo.SwipeTest.test1(SwipeTest.java:30)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="com.volProject.AppiumDemo.CalcTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.volProject.AppiumDemo.CalcTest.test1(CalcTest.java:30)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="com.volProject.AppiumDemo.CalcTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.volProject.AppiumDemo.CalcTest.test2(CalcTest.java:44)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.001" classname="com.volProject.AppiumDemo.SecondTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.volProject.AppiumDemo.SecondTest.test1(SecondTest.java:30)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test1 -->
